# DO NOT EDIT THIS FILE DIRECTLY. This is generated from a literate program
# with the VSCode extension Literate Programming (jesterking.literate).
#
# These literate programs are Rhino 3D scripts explaining how scripting works
# in Rhino 3D with Python.
#
# Read the literate programs at:
#    https://jesterking.github.io/literate
#
# This code is part of the repository:
#    https://github.com/jesterKing/rhipy
#
# The Literate Programming extension repository is at:
#    https://github.com/jesterKing/literate
#
# Licensed under Apache 2.0
# See https://github.com/jesterKing/rhipy/blob/master/LICENSE
#
# Copyright (C) Nathan 'jesterKing' Letwory
#

import os
import rhinoscriptsyntax
import scriptcontext
import Rhino.Render
import System.Convert

def handle_render_content(render_content, target):
    child = render_content.FirstChild
    while child:
        handle_render_content(child, target)
        if child.IsImageBased():
            child.BeginChange(Rhino.Render.RenderContent.ChangeContexts.Program)
            source_path = System.Convert.ToString(child.GetParameter("filename"))
            source_file = os.path.basename(source_path)
            child.SetParameter("filename", target + os.sep + source_file)
            child.EndChange()
        child = child.NextSibling
target = rhinoscriptsyntax.BrowseForFolder()
for render_material in scriptcontext.doc.RenderMaterials:
    handle_render_content(render_material, target)



